const url = new URL("https://example.com/a/b?old=1#frag");
const params = url.searchParams;
console.log(params.get("old"));
console.log(url.search);
params.append("new", "a b");
console.log(url.search);
console.log(url.href);
params.delete("old");
console.log(url.search);
params.set("new", "z");
params.sort();
console.log(url.search);
url.search = "?q=9&r=0";
console.log(url.searchParams.toString());
console.log(url.searchParams.get("q"));
console.log(url.href);
url.search = "k=1";
console.log(url.search);
console.log(url.searchParams.size);
const bare = new URL("https://example.com/x");
console.log(bare.searchParams.size);
bare.searchParams.append("a", "1");
console.log(bare.search);
console.log(bare.href);
