package lower

import "github.com/phongsathornpt/ts-pro/internal/backend/asm/amd64"

func emitAMD64RuntimeSymbols(e *amd64.Emitter, fnOffsets map[string]int) {
	fnOffsets["ts_runtime_init"] = len(e.Code)
	emitAMD64RuntimeInit(e)

	fnOffsets["ts_free_insert"] = len(e.Code)
	emitAMD64FreeInsert(e)
	fnOffsets["ts_gc_set_allocation_start"] = len(e.Code)
	emitAMD64GCSetAllocationStart(e)
	fnOffsets["ts_free_take"] = len(e.Code)
	emitAMD64FreeTake(e, fnOffsets["ts_free_insert"], fnOffsets["ts_gc_set_allocation_start"])

	fnOffsets["ts_gc_mark_payload"] = len(e.Code)
	emitAMD64GCMarkPayload(e)
	fnOffsets["ts_gc_collect"] = len(e.Code)
	emitAMD64GCCollect(e, fnOffsets["ts_gc_mark_payload"], fnOffsets["ts_free_insert"])
	fnOffsets["ts_gc_collections"] = len(e.Code)
	emitAMD64GCMetricNumber(e, amd64RTCollections)
	fnOffsets["ts_gc_reclaimed"] = len(e.Code)
	emitAMD64GCMetricNumber(e, amd64RTReclaimed)
	fnOffsets["ts_gc_mapped_bytes"] = len(e.Code)
	emitAMD64GCMetricNumber(e, amd64RTMappedBytes)

	// Allocation reuses swept blocks first, then bumps in the current chunk,
	// collecting before a new mmap chunk is added.
	fnOffsets["ts_alloc"] = len(e.Code)
	emitAMD64Alloc(e, fnOffsets["ts_gc_collect"], fnOffsets["ts_free_take"])
	fnOffsets["ts_jsvalue_cell_new"] = len(e.Code)
	emitAMD64JSValueCellNew(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_jsvalue_cell_get"] = len(e.Code)
	emitAMD64JSValueCellGet(e)
	fnOffsets["ts_jsvalue_cell_set"] = len(e.Code)
	emitAMD64JSValueCellSet(e)
	fnOffsets["ts_task_trampoline"] = len(e.Code)
	emitAMD64TaskTrampoline(e)
	fnOffsets["ts_task_resume"] = len(e.Code)
	emitAMD64TaskResume(e, fnOffsets["ts_task_trampoline"])
	fnOffsets["ts_task_suspend"] = len(e.Code)
	emitAMD64TaskSuspend(e)
	fnOffsets["ts_task_spawn"] = len(e.Code)
	emitAMD64TaskSpawn(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_microtask_spawn"] = len(e.Code)
	emitAMD64MicrotaskSpawn(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_clock_now_ns"] = len(e.Code)
	emitAMD64ClockNowNS(e)
	fnOffsets["ts_set_timeout"] = len(e.Code)
	emitAMD64SetTimeout(e, fnOffsets["ts_alloc"], fnOffsets["ts_clock_now_ns"])
	fnOffsets["ts_clear_timeout"] = len(e.Code)
	emitAMD64ClearTimeout(e)
	fnOffsets["ts_performance_now"] = len(e.Code)
	emitAMD64PerformanceNow(e, fnOffsets["ts_clock_now_ns"])
	fnOffsets["ts_performance_time_origin"] = len(e.Code)
	emitAMD64PerformanceTimeOrigin(e)
	fnOffsets["ts_nanosleep_ns"] = len(e.Code)
	emitAMD64NanosleepNS(e)
	fnOffsets["ts_task_run_one"] = len(e.Code)
	emitAMD64TaskRunOne(e, fnOffsets["ts_task_resume"], fnOffsets["ts_clock_now_ns"], fnOffsets["ts_nanosleep_ns"])
	fnOffsets["ts_task_drain"] = len(e.Code)
	emitAMD64TaskDrain(e, fnOffsets["ts_task_run_one"])
	fnOffsets["ts_task_join"] = len(e.Code)
	emitAMD64TaskJoin(e, fnOffsets["ts_task_run_one"])
	fnOffsets["ts_task_yield"] = len(e.Code)
	emitAMD64TaskYield(e, fnOffsets["ts_task_run_one"], fnOffsets["ts_task_suspend"])
	fnOffsets["ts_task_sleep"] = len(e.Code)
	emitAMD64TaskSleep(e, fnOffsets["ts_clock_now_ns"], fnOffsets["ts_nanosleep_ns"], fnOffsets["ts_task_suspend"])
	fnOffsets["ts_task_reject"] = len(e.Code)
	emitAMD64TaskReject(e)
	fnOffsets["ts_task_done"] = len(e.Code)
	emitAMD64TaskDone(e)
	fnOffsets["ts_task_rejected"] = len(e.Code)
	emitAMD64TaskRejected(e)
	fnOffsets["ts_task_error"] = len(e.Code)
	emitAMD64TaskError(e)
	fnOffsets["ts_task_cancel"] = len(e.Code)
	emitAMD64TaskCancel(e)
	fnOffsets["ts_task_cancelled"] = len(e.Code)
	emitAMD64TaskCancelled(e)
	fnOffsets["ts_task_set_context"] = len(e.Code)
	emitAMD64TaskSetContext(e)
	fnOffsets["ts_task_context"] = len(e.Code)
	emitAMD64TaskContext(e)
	fnOffsets["ts_task_group_new"] = len(e.Code)
	emitAMD64TaskGroupNew(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_task_group_spawn"] = len(e.Code)
	emitAMD64TaskGroupSpawn(e, fnOffsets["ts_task_spawn"])
	fnOffsets["ts_task_group_join"] = len(e.Code)
	emitAMD64TaskGroupJoin(e, fnOffsets["ts_task_join"])
	fnOffsets["ts_task_group_cancel"] = len(e.Code)
	emitAMD64TaskGroupCancel(e)
	fnOffsets["ts_channel_new"] = len(e.Code)
	emitAMD64ChannelNew(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_channel_try_send"] = len(e.Code)
	emitAMD64ChannelTrySend(e)
	fnOffsets["ts_channel_try_recv_or"] = len(e.Code)
	emitAMD64ChannelTryRecvOr(e)
	fnOffsets["ts_channel_send"] = len(e.Code)
	emitAMD64ChannelSend(e, fnOffsets["ts_channel_try_send"], fnOffsets["ts_task_yield"])
	fnOffsets["ts_channel_recv"] = len(e.Code)
	emitAMD64ChannelRecv(e, fnOffsets["ts_task_yield"])

	fnOffsets["ts_number_to_string"] = len(e.Code)
	emitAMD64NumberToString(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_bool_to_string"] = len(e.Code)
	emitAMD64BoolToString(e, fnOffsets["ts_alloc"])

	fnOffsets["ts_date_from_number"] = len(e.Code)
	emitAMD64DateFromNumber(e)
	fnOffsets["ts_date_now"] = len(e.Code)
	emitAMD64DateNow(e)
	dateGetters := [6]int{}
	for i, name := range []string{"ts_date_get_year", "ts_date_get_month", "ts_date_get_date", "ts_date_get_hours", "ts_date_get_minutes", "ts_date_get_seconds"} {
		fnOffsets[name] = len(e.Code)
		dateGetters[i] = len(e.Code)
		emitAMD64DateGetPart(e, i)
	}
	fnOffsets["ts_date_to_iso"] = len(e.Code)
	emitAMD64DateToISO(e, fnOffsets["ts_alloc"], dateGetters)

	fnOffsets["ts_object_new"] = len(e.Code)
	emitAMD64ObjectNew(e, fnOffsets["ts_alloc"])

	fnOffsets["ts_array_buffer_wrap"] = len(e.Code)
	emitAMD64ArrayBufferWrap(e, fnOffsets["ts_object_new"])
	fnOffsets["ts_uint8_array_wrap"] = len(e.Code)
	emitAMD64Uint8ArrayWrap(e, fnOffsets["ts_object_new"])

	fnOffsets["ts_byte_buffer_new"] = len(e.Code)
	emitAMD64ByteBufferNew(e, fnOffsets["ts_object_new"], fnOffsets["ts_alloc"])
	fnOffsets["ts_byte_buffer_len"] = len(e.Code)
	emitAMD64ByteBufferLength(e)
	fnOffsets["ts_byte_buffer_get"] = len(e.Code)
	emitAMD64ByteBufferGet(e)
	fnOffsets["ts_byte_buffer_set"] = len(e.Code)
	emitAMD64ByteBufferSet(e)
	fnOffsets["ts_byte_buffer_copy"] = len(e.Code)
	emitAMD64ByteBufferCopy(e)

	fnOffsets["ts_byte_buffer_slice"] = len(e.Code)
	emitAMD64ByteBufferSlice(e, fnOffsets["ts_byte_buffer_new"], fnOffsets["ts_byte_buffer_copy"])

	fnOffsets["ts_byte_buffer_from_utf8_string"] = len(e.Code)
	emitAMD64ByteBufferFromUTF8String(e, fnOffsets["ts_byte_buffer_new"])
	fnOffsets["ts_byte_buffer_to_utf8_string"] = len(e.Code)
	emitAMD64ByteBufferToUTF8String(e, fnOffsets["ts_alloc"])

	fnOffsets["ts_http_dechunk"] = len(e.Code)
	emitAMD64HTTPDechunk(e, fnOffsets["ts_byte_buffer_new"])
	fnOffsets["ts_net_hosts_lookup_ipv4"] = len(e.Code)
	emitAMD64NetHostsLookupIPv4(e, fnOffsets["ts_byte_buffer_new"])
	fnOffsets["ts_net_dns_lookup_ipv4"] = len(e.Code)
	emitAMD64NetDNSLookupIPv4(e, fnOffsets["ts_byte_buffer_new"], fnOffsets["ts_task_sleep"])
	fnOffsets["ts_net_resolve_ipv4"] = len(e.Code)
	emitAMD64NetResolveIPv4(e, fnOffsets["ts_byte_buffer_new"], fnOffsets["ts_net_hosts_lookup_ipv4"], fnOffsets["ts_net_dns_lookup_ipv4"])
	fnOffsets["ts_net_parse_ipv6"] = len(e.Code)
	emitAMD64NetParseIPv6(e, fnOffsets["ts_byte_buffer_new"])
	fnOffsets["ts_net_http_request_ipv4"] = len(e.Code)
	emitAMD64NetHTTPRequestIPv4(e, fnOffsets["ts_byte_buffer_new"], fnOffsets["ts_byte_buffer_copy"], fnOffsets["ts_task_yield"])
	fnOffsets["ts_net_http_request_ipv6"] = len(e.Code)
	emitAMD64NetHTTPRequestIPv6(e, fnOffsets["ts_byte_buffer_new"], fnOffsets["ts_byte_buffer_copy"], fnOffsets["ts_task_yield"])

	fnOffsets["ts_utf8_validate"] = len(e.Code)
	emitAMD64UTF8Validate(e)
	fnOffsets["ts_utf8_sanitize"] = len(e.Code)
	emitAMD64UTF8Sanitize(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_text_encode_into"] = len(e.Code)
	emitAMD64TextEncodeInto(e, fnOffsets["ts_object_new"])

	fnOffsets["ts_encoding_label_eq"] = len(e.Code)
	emitAMD64EncodingLabelEq(e)

	fnOffsets["ts_array_new"] = len(e.Code)
	emitAMD64ArrayNew(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_array_get"] = len(e.Code)
	emitAMD64ArrayGet(e)
	fnOffsets["ts_array_set"] = len(e.Code)
	emitAMD64ArraySet(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_array_len"] = len(e.Code)
	emitAMD64ArrayLength(e)
	fnOffsets["ts_array_push"] = len(e.Code)
	emitAMD64ArrayPush(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_array_pop"] = len(e.Code)
	emitAMD64ArrayPop(e)

	fnOffsets["ts_string_len"] = len(e.Code)
	emitAMD64StringLength(e)
	fnOffsets["ts_string_byte_at"] = len(e.Code)
	emitAMD64StringByteAt(e)
	fnOffsets["ts_string_slice_bytes"] = len(e.Code)
	emitAMD64StringSliceBytes(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_string_find_byte"] = len(e.Code)
	emitAMD64StringFindByte(e)
	fnOffsets["ts_string_find_last_byte"] = len(e.Code)
	emitAMD64StringFindLastByte(e)
	fnOffsets["ts_string_find_first_of3"] = len(e.Code)
	emitAMD64StringFindFirstOf3(e)
	fnOffsets["ts_string_ascii_lower"] = len(e.Code)
	emitAMD64StringASCIILower(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_string_ascii_upper"] = len(e.Code)
	emitAMD64StringASCIIUpper(e, fnOffsets["ts_alloc"])

	fnOffsets["ts_hex_nibble"] = len(e.Code)
	emitAMD64HexNibble(e)
	fnOffsets["ts_hex_ascii"] = len(e.Code)
	emitAMD64HexASCII(e)
	fnOffsets["ts_form_url_decode_bytes"] = len(e.Code)
	emitAMD64FormURLDecodeBytes(e, fnOffsets["ts_byte_buffer_new"], fnOffsets["ts_hex_nibble"])
	fnOffsets["ts_form_url_encode"] = len(e.Code)
	emitAMD64FormURLEncode(e, fnOffsets["ts_alloc"], fnOffsets["ts_hex_ascii"])

	fnOffsets["ts_string_eq"] = len(e.Code)
	emitAMD64StringEq(e)
	fnOffsets["ts_string_hash"] = len(e.Code)
	emitAMD64StringHash(e)
	fnOffsets["ts_regexp_test"] = len(e.Code)
	emitAMD64RegExpTest(e)

	fnOffsets["ts_js_key_eq"] = len(e.Code)
	emitAMD64JSKeyEq(e, fnOffsets["ts_string_eq"])
	fnOffsets["ts_collection_new"] = len(e.Code)
	emitAMD64CollectionNew(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_collection_find"] = len(e.Code)
	emitAMD64CollectionFind(e, fnOffsets["ts_js_key_eq"])
	fnOffsets["ts_collection_set"] = len(e.Code)
	emitAMD64CollectionSet(e, fnOffsets["ts_alloc"], fnOffsets["ts_collection_find"])
	fnOffsets["ts_collection_get"] = len(e.Code)
	emitAMD64CollectionGet(e, fnOffsets["ts_collection_find"])
	fnOffsets["ts_collection_has"] = len(e.Code)
	emitAMD64CollectionHas(e, fnOffsets["ts_collection_find"])
	fnOffsets["ts_collection_delete"] = len(e.Code)
	emitAMD64CollectionDelete(e, fnOffsets["ts_collection_find"])
	fnOffsets["ts_collection_clear"] = len(e.Code)
	emitAMD64CollectionClear(e)
	fnOffsets["ts_collection_size"] = len(e.Code)
	emitAMD64CollectionSize(e)

	fnOffsets["ts_event_target_new"] = len(e.Code)
	emitAMD64EventTargetNew(e, fnOffsets["ts_object_new"])
	fnOffsets["ts_event_target_add"] = len(e.Code)
	emitAMD64EventTargetAdd(e, fnOffsets["ts_object_new"], fnOffsets["ts_string_eq"])
	fnOffsets["ts_event_target_remove"] = len(e.Code)
	emitAMD64EventTargetRemove(e, fnOffsets["ts_string_eq"])
	fnOffsets["ts_event_target_next"] = len(e.Code)
	emitAMD64EventTargetNext(e, fnOffsets["ts_string_eq"])
	fnOffsets["ts_event_listener_callback"] = len(e.Code)
	emitAMD64EventListenerCallback(e)
	fnOffsets["ts_event_listener_once"] = len(e.Code)
	emitAMD64EventListenerOnce(e)
	fnOffsets["ts_event_listener_passive"] = len(e.Code)
	emitAMD64EventListenerPassive(e)
	fnOffsets["ts_event_listener_remove"] = len(e.Code)
	emitAMD64EventListenerRemove(e)
	fnOffsets["ts_event_target_tail"] = len(e.Code)
	emitAMD64EventTargetTail(e)
	fnOffsets["ts_null_ref"] = len(e.Code)
	emitAMD64NullRef(e)

	fnOffsets["ts_abort_signal_new"] = len(e.Code)
	emitAMD64AbortSignalNew(e, fnOffsets["ts_object_new"], fnOffsets["ts_jsvalue_cell_new"])
	fnOffsets["ts_abort_signal_aborted"] = len(e.Code)
	emitAMD64AbortSignalAborted(e)
	fnOffsets["ts_abort_signal_reason"] = len(e.Code)
	emitAMD64AbortSignalReason(e)
	fnOffsets["ts_abort_signal_set_reason"] = len(e.Code)
	emitAMD64AbortSignalSetReason(e)
	fnOffsets["ts_abort_signal_onabort"] = len(e.Code)
	emitAMD64AbortSignalOnAbort(e)
	fnOffsets["ts_abort_signal_set_onabort"] = len(e.Code)
	emitAMD64AbortSignalSetOnAbort(e)

	fnOffsets["ts_dynamic_object_new"] = len(e.Code)
	emitAMD64DynamicObjectNew(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_global_object"] = len(e.Code)
	emitAMD64GlobalObject(e, fnOffsets["ts_dynamic_object_new"])
	fnOffsets["ts_dynamic_get"] = len(e.Code)
	emitAMD64DynamicGet(e, fnOffsets["ts_string_eq"], fnOffsets["ts_string_hash"])
	fnOffsets["ts_dynamic_set"] = len(e.Code)
	emitAMD64DynamicSet(e, fnOffsets["ts_alloc"], fnOffsets["ts_string_eq"], fnOffsets["ts_string_hash"])

	fnOffsets["ts_btoa_valid"] = len(e.Code)
	emitAMD64BtoaValid(e)
	fnOffsets["ts_latin1_next"] = len(e.Code)
	emitAMD64Latin1Next(e)
	fnOffsets["ts_base64_char"] = len(e.Code)
	emitAMD64Base64Char(e)
	fnOffsets["ts_btoa"] = len(e.Code)
	emitAMD64Btoa(e, fnOffsets["ts_alloc"], fnOffsets["ts_latin1_next"], fnOffsets["ts_base64_char"])

	fnOffsets["ts_ascii_whitespace"] = len(e.Code)
	emitAMD64ASCIIWhitespace(e)
	fnOffsets["ts_base64_value"] = len(e.Code)
	emitAMD64Base64Value(e)
	fnOffsets["ts_atob_valid"] = len(e.Code)
	emitAMD64AtobValid(e, fnOffsets["ts_ascii_whitespace"], fnOffsets["ts_base64_value"])
	fnOffsets["ts_latin1_write_utf8"] = len(e.Code)
	emitAMD64Latin1WriteUTF8(e)
	fnOffsets["ts_atob"] = len(e.Code)
	emitAMD64Atob(e, fnOffsets["ts_alloc"], fnOffsets["ts_ascii_whitespace"], fnOffsets["ts_base64_value"], fnOffsets["ts_latin1_write_utf8"])

	fnOffsets["ts_string_concat"] = len(e.Code)
	emitAMD64StringConcat(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_string_concat3"] = len(e.Code)
	emitAMD64StringConcatFixed(e, fnOffsets["ts_alloc"], 3)
	fnOffsets["ts_string_concat4"] = len(e.Code)
	emitAMD64StringConcatFixed(e, fnOffsets["ts_alloc"], 4)
	fnOffsets["ts_string_builder_seed"] = len(e.Code)
	emitAMD64StringBuilderSeed(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_string_append_owned"] = len(e.Code)
	emitAMD64StringAppendOwned(e, fnOffsets["ts_alloc"])
	fnOffsets["ts_js_array_to_string"] = len(e.Code)
	emitAMD64JSArrayToString(e, fnOffsets["ts_js_array_to_string"], fnOffsets["ts_alloc"], fnOffsets["ts_number_to_string"], fnOffsets["ts_bool_to_string"], fnOffsets["ts_string_concat"])
	fnOffsets["ts_js_to_string"] = len(e.Code)
	emitAMD64JSToString(e, fnOffsets["ts_alloc"], fnOffsets["ts_number_to_string"], fnOffsets["ts_bool_to_string"], fnOffsets["ts_js_array_to_string"])
	fnOffsets["ts_js_add"] = len(e.Code)
	emitAMD64JSAdd(e, fnOffsets["ts_js_to_string"], fnOffsets["ts_string_concat"], fnOffsets["ts_js_box_number"])
	fnOffsets["ts_js_to_number"] = len(e.Code)
	emitAMD64JSToNumber(e, fnOffsets["ts_js_string_to_number"], fnOffsets["ts_js_array_to_string"])
	for _, spec := range []struct{ name, op string }{
		{"ts_js_sub", "sub"}, {"ts_js_mul", "mul"}, {"ts_js_div", "div"}, {"ts_js_mod", "mod"},
	} {
		fnOffsets[spec.name] = len(e.Code)
		emitAMD64JSNumericBinary(e, fnOffsets["ts_js_to_number"], spec.op)
	}
	fnOffsets["ts_js_strict_eq"] = len(e.Code)
	emitAMD64JSStrictEqual(e, fnOffsets["ts_string_eq"])
	fnOffsets["ts_js_loose_eq"] = len(e.Code)
	emitAMD64JSLooseEqual(e, fnOffsets["ts_js_loose_eq"], fnOffsets["ts_js_strict_eq"], fnOffsets["ts_js_to_number"], fnOffsets["ts_js_to_string"])
	fnOffsets["ts_js_string_compare"] = len(e.Code)
	emitAMD64JSStringCompare(e)
	for _, spec := range []struct{ name, op string }{
		{"ts_js_lt", "lt"}, {"ts_js_le", "le"}, {"ts_js_gt", "gt"}, {"ts_js_ge", "ge"},
	} {
		fnOffsets[spec.name] = len(e.Code)
		emitAMD64JSRelational(e, fnOffsets["ts_js_to_number"], fnOffsets["ts_js_to_string"], fnOffsets["ts_js_string_compare"], spec.op)
	}

	// Emit ts_sys_exit
	fnOffsets["ts_sys_exit"] = len(e.Code)
	emitAMD64SysExit(e)
}
