package lower

import (
	"encoding/binary"

	"github.com/phongsathornpt/ts-pro/internal/backend/asm/amd64"
)

func emitAMD64GCMarkPayload(e *amd64.Emitter) {
	// Internal tracing loops keep R8/R9 live across marker calls. Preserve both
	// even though they are caller-saved in SysV; this helper has a narrower
	// runtime ABI than ordinary generated calls.
	e.Push(amd64.R8)
	e.Push(amd64.R9)
	patchJcc := func(at, target int) { binary.LittleEndian.PutUint32(e.Code[at+2:], uint32(int32(target-(at+6)))) }
	patchJmp := func(at, target int) { binary.LittleEndian.PutUint32(e.Code[at+1:], uint32(int32(target-(at+5)))) }
	// Accept raw payload pointers and NaN-boxed JSValue references.
	e.MovRegReg(amd64.RAX, amd64.RDI)
	e.MovRegImm64(amd64.R10, amd64JSTagMask)
	e.AndRegReg(amd64.RAX, amd64.R10)
	e.MovRegImm64(amd64.R10, amd64JSStringTag)
	e.CmpRegReg(amd64.RAX, amd64.R10)
	isTaggedString := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegImm64(amd64.R10, amd64JSRefTag)
	e.CmpRegReg(amd64.RAX, amd64.R10)
	rawPayload := len(e.Code)
	e.JccRel32(amd64.CondNE, 0)
	taggedPayload := len(e.Code)
	patchJcc(isTaggedString, taggedPayload)
	e.MovRegImm64(amd64.R10, amd64JSPayloadMask)
	e.AndRegReg(amd64.RDI, amd64.R10)
	patchJcc(rawPayload, len(e.Code))
	e.TestRegReg(amd64.RDI, amd64.RDI)
	nilJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.RDI)
	e.SubRegImm32(amd64.R10, amd64ObjectHeaderSize)

	// Most references during graph traversal have chunk locality. Probe the last
	// successful chunk first, then fall back to the complete linked chunk list.
	e.MovRegDeref(amd64.R11, amd64.R15, amd64RTMarkChunk)
	e.TestRegReg(amd64.R11, amd64.R11)
	cacheEmpty := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.RAX, amd64.R11)
	e.AddRegImm32(amd64.RAX, amd64ChunkSize)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	cacheBelow := len(e.Code)
	e.JccRel32(amd64.CondB, 0)
	e.MovRegDeref(amd64.RAX, amd64.R11, amd64ChunkUsed)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	cacheAbove := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	cacheHit := len(e.Code)
	e.JmpRel32(0)

	scanStart := len(e.Code)
	patchJcc(cacheEmpty, scanStart)
	patchJcc(cacheBelow, scanStart)
	patchJcc(cacheAbove, scanStart)
	e.MovRegDeref(amd64.R11, amd64.R15, amd64RTChunkHead)
	loop := len(e.Code)
	e.TestRegReg(amd64.R11, amd64.R11)
	missJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.RAX, amd64.R11)
	e.AddRegImm32(amd64.RAX, amd64ChunkSize)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	nextBelow := len(e.Code)
	e.JccRel32(amd64.CondB, 0)
	e.MovRegDeref(amd64.RAX, amd64.R11, amd64ChunkUsed)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	nextAbove := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	// Cache the successful chunk for subsequent nearby references.
	e.MovDerefReg(amd64.R15, amd64RTMarkChunk, amd64.R11)
	foundChunk := len(e.Code)
	patchJmp(cacheHit, foundChunk)

	// Range membership alone is insufficient: require the allocation-start
	// bitmap bit for this 16-byte-aligned header. This keeps exact interior-
	// pointer rejection O(1) instead of walking every prior object in the chunk.
	emitAMD64ChunkBitIndex(e, amd64.R9, amd64.R11, amd64.R10)
	e.BtDerefReg(amd64.R11, amd64ChunkAllocBitmap, amd64.R9)
	allocationStartMiss := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	e.MovRegDeref(amd64.RAX, amd64.R10, amd64ObjectFlags)
	e.CmpRegImm32(amd64.RAX, 1)
	alreadyMarked := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, 2)
	freeJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegImm64(amd64.RAX, 1)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RAX)

	// Keep sparse discovery on the existing object-work fast path. Only after a
	// chunk has accumulated enough newly marked objects do later discoveries go
	// to its local pending list, amortizing queue metadata over dense work.
	e.MovRegDeref(amd64.RAX, amd64.R11, amd64ChunkDenseCount)
	e.CmpRegImm32(amd64.RAX, amd64GCDensePromotionThreshold)
	denseWork := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	e.AddRegImm32(amd64.RAX, 1)
	e.MovDerefReg(amd64.R11, amd64ChunkDenseCount, amd64.RAX)
	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTMarkStack)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.RAX)
	e.MovDerefReg(amd64.R15, amd64RTMarkStack, amd64.R10)
	markQueued := len(e.Code)
	e.JmpRel32(0)

	denseWorkLabel := len(e.Code)
	patchJcc(denseWork, denseWorkLabel)
	e.MovRegDeref(amd64.RAX, amd64.R11, amd64ChunkDenseHead)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.RAX)
	e.MovDerefReg(amd64.R11, amd64ChunkDenseHead, amd64.R10)
	e.MovRegDeref(amd64.RAX, amd64.R11, amd64ChunkDenseQueued)
	e.TestRegReg(amd64.RAX, amd64.RAX)
	alreadyDenseQueued := len(e.Code)
	e.JccRel32(amd64.CondNE, 0)
	e.MovRegImm64(amd64.RAX, 1)
	e.MovDerefReg(amd64.R11, amd64ChunkDenseQueued, amd64.RAX)
	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTDenseChunkStack)
	e.MovDerefReg(amd64.R11, amd64ChunkDenseNext, amd64.RAX)
	e.MovDerefReg(amd64.R15, amd64RTDenseChunkStack, amd64.R11)
	alreadyDenseQueuedLabel := len(e.Code)
	patchJcc(alreadyDenseQueued, alreadyDenseQueuedLabel)

	markQueuedLabel := len(e.Code)
	patchJmp(markQueued, markQueuedLabel)
	e.Pop(amd64.R9)
	e.Pop(amd64.R8)
	e.Ret()
	next := len(e.Code)
	patchJcc(nextBelow, next)
	patchJcc(nextAbove, next)
	e.MovRegDeref(amd64.R11, amd64.R11, amd64ChunkNext)
	back := len(e.Code)
	e.JmpRel32(0)
	patchJmp(back, loop)
	zero := len(e.Code)
	patchJcc(nilJump, zero)
	patchJcc(missJump, zero)
	patchJcc(allocationStartMiss, zero)
	patchJcc(alreadyMarked, zero)
	patchJcc(freeJump, zero)
	e.MovRegImm64(amd64.RAX, 0)
	e.Pop(amd64.R9)
	e.Pop(amd64.R8)
	e.Ret()
}

func emitAMD64GCCollect(e *amd64.Emitter, markOffset, freeInsertOffset int) {
	patchJcc := func(at, target int) {
		binary.LittleEndian.PutUint32(e.Code[at+2:], uint32(int32(target-(at+6))))
	}
	patchJmp := func(at, target int) {
		binary.LittleEndian.PutUint32(e.Code[at+1:], uint32(int32(target-(at+5))))
	}

	e.Push(amd64.RBP)
	e.MovRegReg(amd64.RBP, amd64.RSP)
	e.Push(amd64.RBX)
	e.Push(amd64.R12)
	e.Push(amd64.R13)
	e.Push(amd64.R14)

	// collectionCount++
	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTCollections)
	e.AddRegImm32(amd64.RAX, 1)
	e.MovDerefReg(amd64.R15, amd64RTCollections, amd64.RAX)

	// Reset object work plus dense-chunk scheduling metadata for this cycle.
	e.MovRegImm64(amd64.RAX, 0)
	e.MovDerefReg(amd64.R15, amd64RTMarkStack, amd64.RAX)
	e.MovDerefReg(amd64.R15, amd64RTDenseChunkStack, amd64.RAX)
	e.MovRegDeref(amd64.R10, amd64.R15, amd64RTChunkHead)
	resetDenseLoop := len(e.Code)
	e.TestRegReg(amd64.R10, amd64.R10)
	resetDenseDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	for _, off := range []int32{amd64ChunkDenseHead, amd64ChunkDenseNext, amd64ChunkDenseCount, amd64ChunkDenseQueued} {
		e.MovDerefReg(amd64.R10, off, amd64.RAX)
	}
	e.MovRegDeref(amd64.R10, amd64.R10, amd64ChunkNext)
	resetDenseBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(resetDenseBack, resetDenseLoop)
	resetDenseDoneLabel := len(e.Code)
	patchJcc(resetDenseDone, resetDenseDoneLabel)
	// Start pointer validation from the current chunk, then retain locality hints
	// as marking walks into older chunks.
	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTChunkHead)
	e.MovDerefReg(amd64.R15, amd64RTMarkChunk, amd64.RAX)

	// Mark exact roots from the linked shadow-root frames.
	e.MovRegDeref(amd64.R12, amd64.R15, amd64RTRootHead)
	frameLoop := len(e.Code)
	e.TestRegReg(amd64.R12, amd64.R12)
	markDoneJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R13, amd64.R12, 8) // root count
	e.MovRegReg(amd64.R14, amd64.R12)
	e.AddRegImm32(amd64.R14, 16) // first root slot

	rootLoop := len(e.Code)
	e.TestRegReg(amd64.R13, amd64.R13)
	frameNextJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R14, 0)
	markRootCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markRootCall + 5)))
	e.AddRegImm32(amd64.R14, 8)
	e.SubRegImm32(amd64.R13, 1)
	rootBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(rootBack, rootLoop)

	frameNext := len(e.Code)
	patchJcc(frameNextJump, frameNext)
	e.MovRegDeref(amd64.R12, amd64.R12, 0)
	frameBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(frameBack, frameLoop)

	markDone := len(e.Code)
	patchJcc(markDoneJump, markDone)

	// The runnable queue is a runtime-owned GC root. Marking its head is enough
	// because task tracing follows the next pointer through the complete queue.
	e.MovRegDeref(amd64.RDI, amd64.R15, amd64RTTaskHead)
	markTaskQueueCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskQueueCall + 5)))
	e.MovRegDeref(amd64.RDI, amd64.R15, amd64RTTimerHead)
	markTimerQueueCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTimerQueueCall + 5)))
	e.MovRegDeref(amd64.RDI, amd64.R15, amd64RTCurrentTask)
	markCurrentTaskCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markCurrentTaskCall + 5)))

	// Drain ordinary object work first. If it empties, take one pending object
	// from the current dense chunk; the chunk remains queued until its local list
	// is exhausted so nearby objects retain physical locality.
	traceWorkLoop := len(e.Code)
	e.MovRegDeref(amd64.R12, amd64.R15, amd64RTMarkStack)
	e.TestRegReg(amd64.R12, amd64.R12)
	tryDenseWork := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R13, amd64.R12, amd64ObjectNextFree)
	e.MovDerefReg(amd64.R15, amd64RTMarkStack, amd64.R13)
	workReady := len(e.Code)
	e.JmpRel32(0)

	tryDenseWorkLabel := len(e.Code)
	patchJcc(tryDenseWork, tryDenseWorkLabel)
	e.MovRegDeref(amd64.R13, amd64.R15, amd64RTDenseChunkStack)
	e.TestRegReg(amd64.R13, amd64.R13)
	traceDoneJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R12, amd64.R13, amd64ChunkDenseHead)
	e.TestRegReg(amd64.R12, amd64.R12)
	denseChunkEmpty := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RAX, amd64.R12, amd64ObjectNextFree)
	e.MovDerefReg(amd64.R13, amd64ChunkDenseHead, amd64.RAX)
	denseWorkReady := len(e.Code)
	e.JmpRel32(0)

	denseChunkEmptyLabel := len(e.Code)
	patchJcc(denseChunkEmpty, denseChunkEmptyLabel)
	e.MovRegDeref(amd64.RAX, amd64.R13, amd64ChunkDenseNext)
	e.MovDerefReg(amd64.R15, amd64RTDenseChunkStack, amd64.RAX)
	e.MovRegImm64(amd64.RAX, 0)
	e.MovDerefReg(amd64.R13, amd64ChunkDenseNext, amd64.RAX)
	e.MovDerefReg(amd64.R13, amd64ChunkDenseQueued, amd64.RAX)
	denseRetry := len(e.Code)
	e.JmpRel32(0)
	patchJmp(denseRetry, traceWorkLoop)

	workReadyLabel := len(e.Code)
	patchJmp(workReady, workReadyLabel)
	patchJmp(denseWorkReady, workReadyLabel)
	e.MovRegImm64(amd64.RAX, 0)
	e.MovDerefReg(amd64.R12, amd64ObjectNextFree, amd64.RAX)
	e.MovRegDeref(amd64.RAX, amd64.R12, amd64ObjectType)
	traceJumps := make(map[amd64GCTraceKind]int, len(amd64GCLayouts))
	for _, desc := range amd64GCLayouts {
		if desc.TraceKind == amd64GCTraceAtomic {
			continue
		}
		e.CmpRegImm32(amd64.RAX, int32(desc.ObjectType))
		traceJumps[desc.TraceKind] = len(e.Code)
		e.JccRel32(amd64.CondE, 0)
	}
	patchTrace := func(kind amd64GCTraceKind, target int) {
		if at, ok := traceJumps[kind]; ok {
			patchJcc(at, target)
		}
	}
	traceAfterChildrenJump := len(e.Code)
	e.JmpRel32(0)

	traceArray := len(e.Code)
	patchTrace(amd64GCTraceArray, traceArray)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64ArrayData)
	markArrayChildCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markArrayChildCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceArrayDone := len(e.Code)
	e.JmpRel32(0)

	traceRefData := len(e.Code)
	patchTrace(amd64GCTraceRefData, traceRefData)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectSize)
	e.SubRegImm32(amd64.R9, amd64ObjectHeaderSize)
	e.ShrRegImm8(amd64.R9, 3)
	refSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	refSlotsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markRefCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markRefCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.R8, 8)
	e.SubRegImm32(amd64.R9, 1)
	refSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(refSlotBack, refSlotLoop)
	refSlotsDoneLabel := len(e.Code)
	patchJcc(refSlotsDone, refSlotsDoneLabel)
	traceRefDataDone := len(e.Code)
	e.JmpRel32(0)

	traceObjectFields := len(e.Code)
	patchTrace(amd64GCTraceObject, traceObjectFields)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize+amd64ObjectFields)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectHeaderSize+amd64ObjectRefMask)
	objectFieldLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	objectFieldsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.R9)
	e.MovRegImm64(amd64.R11, 1)
	e.AndRegReg(amd64.R10, amd64.R11)
	e.TestRegReg(amd64.R10, amd64.R10)
	skipObjectField := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markObjectFieldCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markObjectFieldCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	objectFieldNext := len(e.Code)
	patchJcc(skipObjectField, objectFieldNext)
	e.AddRegImm32(amd64.R8, 8)
	e.ShrRegImm8(amd64.R9, 1)
	objectFieldBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(objectFieldBack, objectFieldLoop)
	objectFieldsDoneLabel := len(e.Code)
	patchJcc(objectFieldsDone, objectFieldsDoneLabel)
	traceObjectDone := len(e.Code)
	e.JmpRel32(0)

	// JSValue backing stores trace only tagged heap references.
	traceJSValueData := len(e.Code)
	patchTrace(amd64GCTraceJSValueData, traceJSValueData)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectSize)
	e.SubRegImm32(amd64.R9, amd64ObjectHeaderSize)
	e.ShrRegImm8(amd64.R9, 3)
	jsSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	jsSlotsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markJSCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markJSCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.R8, 8)
	e.SubRegImm32(amd64.R9, 1)
	jsSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(jsSlotBack, jsSlotLoop)
	jsSlotsDoneLabel := len(e.Code)
	patchJcc(jsSlotsDone, jsSlotsDoneLabel)
	traceJSValueDataDone := len(e.Code)
	e.JmpRel32(0)

	// Dynamic object identity owns one raw pointer to its growable entry table.
	traceDynamicObject := len(e.Code)
	patchTrace(amd64GCTraceDynamicObject, traceDynamicObject)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64DynamicEntries)
	markDynamicEntriesCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markDynamicEntriesCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceDynamicObjectDone := len(e.Code)
	e.JmpRel32(0)

	// Dynamic hash entries are {hash, raw string key, boxed JSValue}. Hash words
	// are scalars and must never be interpreted as heap references.
	traceDynamicEntries := len(e.Code)
	patchTrace(amd64GCTraceDynamicEntries, traceDynamicEntries)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.RAX, amd64.R12, amd64ObjectSize)
	e.SubRegImm32(amd64.RAX, amd64ObjectHeaderSize)
	e.ShrRegImm8(amd64.RAX, 3) // payload qwords
	e.MovRegImm64(amd64.R11, 3)
	e.Cqo()
	e.IdivReg(amd64.R11)
	e.MovRegReg(amd64.R9, amd64.RAX) // entry count = qwords / 3
	dynamicEntryLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	dynamicEntriesDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, amd64DynamicEntryKey)
	markDynamicKeyCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markDynamicKeyCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R8, amd64DynamicEntryValue)
	markDynamicValueCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markDynamicValueCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.R8, amd64DynamicEntrySize)
	e.SubRegImm32(amd64.R9, 1)
	dynamicEntryBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(dynamicEntryBack, dynamicEntryLoop)
	dynamicEntriesDoneLabel := len(e.Code)
	patchJcc(dynamicEntriesDone, dynamicEntriesDoneLabel)
	traceDynamicEntriesDone := len(e.Code)
	e.JmpRel32(0)

	// Closure payload: code pointer, capture count, reference mask, captures.
	// Only bits set in the capture reference mask are traced.
	traceClosure := len(e.Code)
	patchTrace(amd64GCTraceClosure, traceClosure)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize+24)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectHeaderSize+16)
	closureCaptureLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	closureCapturesDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.R9)
	e.MovRegImm64(amd64.R11, 1)
	e.AndRegReg(amd64.R10, amd64.R11)
	e.TestRegReg(amd64.R10, amd64.R10)
	skipClosureCapture := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markClosureCaptureCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markClosureCaptureCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	closureCaptureNext := len(e.Code)
	patchJcc(skipClosureCapture, closureCaptureNext)
	e.AddRegImm32(amd64.R8, 8)
	e.ShrRegImm8(amd64.R9, 1)
	closureCaptureBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(closureCaptureBack, closureCaptureLoop)
	closureCapturesDoneLabel := len(e.Code)
	patchJcc(closureCapturesDone, closureCapturesDoneLabel)
	traceClosureDone := len(e.Code)
	e.JmpRel32(0)

	traceTask := len(e.Code)
	patchTrace(amd64GCTraceTask, traceTask)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskClosure)
	markTaskClosureCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskClosureCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskNext)
	markTaskNextCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskNextCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskParent)
	markTaskParentCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskParentCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskContext)
	markTaskContextCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskContextCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskGroupNext)
	markTaskGroupNextCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskGroupNextCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)

	// A suspended task owns a precise-root chain on its private native stack.
	// Walk those frames exactly like the active runtime root chain.
	e.MovRegDeref(amd64.R8, amd64.R12, amd64ObjectHeaderSize+amd64TaskSavedRoot)
	taskRootFrameLoop := len(e.Code)
	e.TestRegReg(amd64.R8, amd64.R8)
	taskRootsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R9, amd64.R8, 8)
	e.MovRegReg(amd64.RDX, amd64.R8)
	e.AddRegImm32(amd64.RDX, 16)
	taskRootSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	taskRootFrameNext := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.RDX, 0)
	markTaskSavedRootCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskSavedRootCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.RDX, 8)
	e.SubRegImm32(amd64.R9, 1)
	taskRootSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(taskRootSlotBack, taskRootSlotLoop)
	taskRootFrameNextLabel := len(e.Code)
	patchJcc(taskRootFrameNext, taskRootFrameNextLabel)
	e.MovRegDeref(amd64.R8, amd64.R8, 0)
	taskRootFrameBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(taskRootFrameBack, taskRootFrameLoop)
	taskRootsDoneLabel := len(e.Code)
	patchJcc(taskRootsDone, taskRootsDoneLabel)

	// While a nested child runs, its return-root chain belongs to the caller
	// stack that resumed it. Trace it until the child yields/completes and clears
	// the return context.
	e.MovRegDeref(amd64.R8, amd64.R12, amd64ObjectHeaderSize+amd64TaskReturnRoot)
	taskReturnFrameLoop := len(e.Code)
	e.TestRegReg(amd64.R8, amd64.R8)
	taskReturnRootsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R9, amd64.R8, 8)
	e.MovRegReg(amd64.RDX, amd64.R8)
	e.AddRegImm32(amd64.RDX, 16)
	taskReturnSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	taskReturnFrameNext := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.RDX, 0)
	markTaskReturnRootCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskReturnRootCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.RDX, 8)
	e.SubRegImm32(amd64.R9, 1)
	taskReturnSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(taskReturnSlotBack, taskReturnSlotLoop)
	taskReturnFrameNextLabel := len(e.Code)
	patchJcc(taskReturnFrameNext, taskReturnFrameNextLabel)
	e.MovRegDeref(amd64.R8, amd64.R8, 0)
	taskReturnFrameBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(taskReturnFrameBack, taskReturnFrameLoop)
	taskReturnRootsDoneLabel := len(e.Code)
	patchJcc(taskReturnRootsDone, taskReturnRootsDoneLabel)

	// Rejection reasons are always JSValue payloads regardless of the declared
	// fulfilled result kind. Fulfilled tasks only trace ref/JS result classes.
	e.MovRegDeref(amd64.R10, amd64.R12, amd64ObjectHeaderSize+amd64TaskState)
	e.CmpRegImm32(amd64.R10, 3)
	traceRejectedResult := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R10, amd64.R12, amd64ObjectHeaderSize+amd64TaskKind)
	e.CmpRegImm32(amd64.R10, int32(amd64TaskResultRef))
	traceTaskResult := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	traceTaskDone := len(e.Code)
	e.JmpRel32(0)
	traceTaskResultLabel := len(e.Code)
	patchJcc(traceRejectedResult, traceTaskResultLabel)
	patchJcc(traceTaskResult, traceTaskResultLabel)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskResult)
	markTaskResultCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskResultCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceTaskResultDone := len(e.Code)
	e.JmpRel32(0)

	traceCollection := len(e.Code)
	patchTrace(amd64GCTraceCollection, traceCollection)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64CollectionEntries)
	markCollectionEntriesCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markCollectionEntriesCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceCollectionDone := len(e.Code)
	e.JmpRel32(0)

	traceTaskGroup := len(e.Code)
	patchTrace(amd64GCTraceTaskGroup, traceTaskGroup)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskGroupHead)
	markTaskGroupHeadCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskGroupHeadCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceTaskGroupDone := len(e.Code)
	e.JmpRel32(0)

	traceChannel := len(e.Code)
	patchTrace(amd64GCTraceChannel, traceChannel)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64ChannelData)
	markChannelDataCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markChannelDataCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64ChannelPending)
	markChannelPendingCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markChannelPendingCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceChannelDone := len(e.Code)
	e.JmpRel32(0)

	traceChildrenDone := len(e.Code)
	patchJmp(traceAfterChildrenJump, traceChildrenDone)
	patchJmp(traceArrayDone, traceChildrenDone)
	patchJmp(traceRefDataDone, traceChildrenDone)
	patchJmp(traceObjectDone, traceChildrenDone)
	patchJmp(traceJSValueDataDone, traceChildrenDone)
	patchJmp(traceDynamicObjectDone, traceChildrenDone)
	patchJmp(traceDynamicEntriesDone, traceChildrenDone)
	patchJmp(traceClosureDone, traceChildrenDone)
	patchJmp(traceTaskDone, traceChildrenDone)
	patchJmp(traceTaskResultDone, traceChildrenDone)
	patchJmp(traceChannelDone, traceChildrenDone)
	patchJmp(traceTaskGroupDone, traceChildrenDone)
	patchJmp(traceCollectionDone, traceChildrenDone)
	traceWorkBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(traceWorkBack, traceWorkLoop)
	traceDone := len(e.Code)
	patchJcc(traceDoneJump, traceDone)

	// Sweep every object in every chunk. R12 is the rebuilt free-list head;
	// R14 accumulates bytes newly reclaimed by this collection.
	e.MovRegImm64(amd64.R12, 0)
	e.MovRegImm64(amd64.R14, 0)
	e.MovRegDeref(amd64.R13, amd64.R15, amd64RTChunkHead)

	sweepChunkLoop := len(e.Code)
	e.TestRegReg(amd64.R13, amd64.R13)
	sweepDoneJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.R13)
	e.AddRegImm32(amd64.R10, amd64ChunkSize)
	e.MovRegDeref(amd64.R11, amd64.R13, amd64ChunkUsed)
	e.MovRegImm64(amd64.R8, 0) // previous free header in this chunk

	sweepObjectLoop := len(e.Code)
	e.CmpRegReg(amd64.R10, amd64.R11)
	nextChunkJump := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	e.MovRegDeref(amd64.RBX, amd64.R10, amd64ObjectSize)
	e.MovRegDeref(amd64.RAX, amd64.R10, amd64ObjectFlags)
	e.CmpRegImm32(amd64.RAX, 1)
	liveJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, 2)
	alreadyFreeJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)

	// Newly unreachable object.
	e.MovRegImm64(amd64.RAX, 2)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RAX)
	e.AddRegReg(amd64.R14, amd64.RBX)
	newlyFreeJump := len(e.Code)
	e.JmpRel32(0)

	alreadyFree := len(e.Code)
	patchJcc(alreadyFreeJump, alreadyFree)

	freeObject := len(e.Code)
	patchJmp(newlyFreeJump, freeObject)
	// Coalesce with the immediately preceding free object in this chunk.
	e.TestRegReg(amd64.R8, amd64.R8)
	linkFree := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RAX, amd64.R8, amd64ObjectSize)
	e.MovRegReg(amd64.RDX, amd64.R8)
	e.AddRegReg(amd64.RDX, amd64.RAX)
	e.CmpRegReg(amd64.RDX, amd64.R10)
	notAdjacent := len(e.Code)
	e.JccRel32(amd64.CondNE, 0)
	// Current header is absorbed into the preceding free block. Remove its
	// allocation-start bit so an interior pointer can never resurrect it later.
	emitAMD64ChunkBitIndex(e, amd64.RDX, amd64.R13, amd64.R10)
	e.BtrDerefReg(amd64.R13, amd64ChunkAllocBitmap, amd64.RDX)
	e.AddRegReg(amd64.RAX, amd64.RBX)
	e.MovDerefReg(amd64.R8, amd64ObjectSize, amd64.RAX)
	mergedJump := len(e.Code)
	e.JmpRel32(0)

	linkFreeLabel := len(e.Code)
	patchJcc(linkFree, linkFreeLabel)
	patchJcc(notAdjacent, linkFreeLabel)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.R12)
	e.MovRegReg(amd64.R12, amd64.R10)
	e.MovRegReg(amd64.R8, amd64.R10)
	linkedJump := len(e.Code)
	e.JmpRel32(0)

	live := len(e.Code)
	patchJcc(liveJump, live)
	e.MovRegImm64(amd64.RAX, 0)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RAX)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.RAX)
	e.MovRegImm64(amd64.R8, 0)

	objectNext := len(e.Code)
	patchJmp(mergedJump, objectNext)
	patchJmp(linkedJump, objectNext)
	e.AddRegReg(amd64.R10, amd64.RBX)
	objectBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(objectBack, sweepObjectLoop)

	nextChunk := len(e.Code)
	patchJcc(nextChunkJump, nextChunk)
	e.MovRegDeref(amd64.R13, amd64.R13, amd64ChunkNext)
	chunkBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(chunkBack, sweepChunkLoop)

	sweepDone := len(e.Code)
	patchJcc(sweepDoneJump, sweepDone)

	// Partition the coalesced sweep list into size-class heads. Keeping
	// coalescing single-list based avoids class migration while adjacent free
	// objects are still being merged.
	e.MovRegImm64(amd64.RAX, 0)
	for _, off := range []int32{amd64RTFreeList, amd64RTFree128, amd64RTFree512, amd64RTFree2048, amd64RTFree8192} {
		e.MovDerefReg(amd64.R15, off, amd64.RAX)
	}
	partitionLoop := len(e.Code)
	e.TestRegReg(amd64.R12, amd64.R12)
	partitionDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R13, amd64.R12, amd64ObjectNextFree)
	e.MovRegReg(amd64.RDI, amd64.R12)
	insertCall := len(e.Code)
	e.CallRel32(int32(freeInsertOffset - (insertCall + 5)))
	e.MovRegReg(amd64.R12, amd64.R13)
	partitionBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(partitionBack, partitionLoop)
	partitionDoneLabel := len(e.Code)
	patchJcc(partitionDone, partitionDoneLabel)

	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTReclaimed)
	e.AddRegReg(amd64.RAX, amd64.R14)
	e.MovDerefReg(amd64.R15, amd64RTReclaimed, amd64.RAX)

	e.Pop(amd64.R14)
	e.Pop(amd64.R13)
	e.Pop(amd64.R12)
	e.Pop(amd64.RBX)
	e.Pop(amd64.RBP)
	e.Ret()
}

func emitAMD64GCMetricNumber(e *amd64.Emitter, contextOffset int32) {
	e.MovRegDeref(amd64.RAX, amd64.R15, contextOffset)
	e.Cvtsi2sd(amd64.XMM0, amd64.RAX)
	e.Ret()
}
