package lower

import (
	"encoding/binary"

	"github.com/phongsathornpt/ts-pro/internal/backend/asm/amd64"
)

func emitAMD64GCMarkPayload(e *amd64.Emitter) {
	// Internal tracing loops keep R8 live across marker calls. Preserve it even
	// though it is caller-saved in SysV; this helper has a narrower runtime ABI.
	e.Push(amd64.R8)
	patchJcc := func(at, target int) { binary.LittleEndian.PutUint32(e.Code[at+2:], uint32(int32(target-(at+6)))) }
	patchJmp := func(at, target int) { binary.LittleEndian.PutUint32(e.Code[at+1:], uint32(int32(target-(at+5)))) }
	// Accept raw payload pointers and NaN-boxed JSValue references.
	e.MovRegReg(amd64.RAX, amd64.RDI)
	e.MovRegImm64(amd64.R10, amd64JSTagMask)
	e.AndRegReg(amd64.RAX, amd64.R10)
	e.MovRegImm64(amd64.R10, amd64JSStringTag)
	e.CmpRegReg(amd64.RAX, amd64.R10)
	isTaggedString := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegImm64(amd64.R10, amd64JSRefTag)
	e.CmpRegReg(amd64.RAX, amd64.R10)
	rawPayload := len(e.Code)
	e.JccRel32(amd64.CondNE, 0)
	taggedPayload := len(e.Code)
	patchJcc(isTaggedString, taggedPayload)
	e.MovRegImm64(amd64.R10, amd64JSPayloadMask)
	e.AndRegReg(amd64.RDI, amd64.R10)
	patchJcc(rawPayload, len(e.Code))
	e.TestRegReg(amd64.RDI, amd64.RDI)
	nilJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.RDI)
	e.SubRegImm32(amd64.R10, amd64ObjectHeaderSize)

	// Most references during graph traversal have chunk locality. Probe the last
	// successful chunk first, then fall back to the complete linked chunk list.
	e.MovRegDeref(amd64.R11, amd64.R15, amd64RTMarkChunk)
	e.TestRegReg(amd64.R11, amd64.R11)
	cacheEmpty := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.RAX, amd64.R11)
	e.AddRegImm32(amd64.RAX, amd64ChunkSize)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	cacheBelow := len(e.Code)
	e.JccRel32(amd64.CondB, 0)
	e.MovRegDeref(amd64.RAX, amd64.R11, amd64ChunkUsed)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	cacheAbove := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	cacheHit := len(e.Code)
	e.JmpRel32(0)

	scanStart := len(e.Code)
	patchJcc(cacheEmpty, scanStart)
	patchJcc(cacheBelow, scanStart)
	patchJcc(cacheAbove, scanStart)
	e.MovRegDeref(amd64.R11, amd64.R15, amd64RTChunkHead)
	loop := len(e.Code)
	e.TestRegReg(amd64.R11, amd64.R11)
	missJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.RAX, amd64.R11)
	e.AddRegImm32(amd64.RAX, amd64ChunkSize)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	nextBelow := len(e.Code)
	e.JccRel32(amd64.CondB, 0)
	e.MovRegDeref(amd64.RAX, amd64.R11, amd64ChunkUsed)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	nextAbove := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	// Cache the successful chunk for subsequent nearby references.
	e.MovDerefReg(amd64.R15, amd64RTMarkChunk, amd64.R11)
	foundChunk := len(e.Code)
	patchJmp(cacheHit, foundChunk)

	// Range membership alone is insufficient: an interior pointer can land
	// inside a valid chunk and make payload bytes look like a fake header. Walk
	// the chunk's object chain and require an exact allocation-start match.
	e.MovRegReg(amd64.R8, amd64.R11)
	e.AddRegImm32(amd64.R8, amd64ChunkSize)
	objectStartLoop := len(e.Code)
	e.CmpRegReg(amd64.R8, amd64.R10)
	exactStart := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegReg(amd64.R8, amd64.R10)
	interiorMiss := len(e.Code)
	e.JccRel32(amd64.CondA, 0)
	e.MovRegDeref(amd64.RAX, amd64.R8, amd64ObjectSize)
	e.TestRegReg(amd64.RAX, amd64.RAX)
	zeroSizeMiss := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.AddRegReg(amd64.R8, amd64.RAX)
	objectStartBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(objectStartBack, objectStartLoop)

	exactStartLabel := len(e.Code)
	patchJcc(exactStart, exactStartLabel)
	e.MovRegDeref(amd64.RAX, amd64.R10, amd64ObjectFlags)
	e.CmpRegImm32(amd64.RAX, 1)
	alreadyMarked := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, 2)
	freeJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegImm64(amd64.RAX, 1)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RAX)
	// During marking, amd64RTFreeList is repurposed as an intrusive mark stack.
	// Sweep rebuilds the actual free list after all reachable objects are traced.
	e.MovRegDeref(amd64.R11, amd64.R15, amd64RTFreeList)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.R11)
	e.MovDerefReg(amd64.R15, amd64RTFreeList, amd64.R10)
	e.Pop(amd64.R8)
	e.Ret()
	next := len(e.Code)
	patchJcc(nextBelow, next)
	patchJcc(nextAbove, next)
	e.MovRegDeref(amd64.R11, amd64.R11, amd64ChunkNext)
	back := len(e.Code)
	e.JmpRel32(0)
	patchJmp(back, loop)
	zero := len(e.Code)
	patchJcc(nilJump, zero)
	patchJcc(missJump, zero)
	patchJcc(interiorMiss, zero)
	patchJcc(zeroSizeMiss, zero)
	patchJcc(alreadyMarked, zero)
	patchJcc(freeJump, zero)
	e.MovRegImm64(amd64.RAX, 0)
	e.Pop(amd64.R8)
	e.Ret()
}

func emitAMD64GCCollect(e *amd64.Emitter, markOffset int) {
	patchJcc := func(at, target int) {
		binary.LittleEndian.PutUint32(e.Code[at+2:], uint32(int32(target-(at+6))))
	}
	patchJmp := func(at, target int) {
		binary.LittleEndian.PutUint32(e.Code[at+1:], uint32(int32(target-(at+5))))
	}

	e.Push(amd64.RBP)
	e.MovRegReg(amd64.RBP, amd64.RSP)
	e.Push(amd64.RBX)
	e.Push(amd64.R12)
	e.Push(amd64.R13)
	e.Push(amd64.R14)

	// collectionCount++
	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTCollections)
	e.AddRegImm32(amd64.RAX, 1)
	e.MovDerefReg(amd64.R15, amd64RTCollections, amd64.RAX)

	// The reclaimed-block list is rebuilt by sweep. Reuse its head as the mark
	// worklist so tracing needs no allocation and each live object is visited once.
	e.MovRegImm64(amd64.RAX, 0)
	e.MovDerefReg(amd64.R15, amd64RTFreeList, amd64.RAX)
	// Start pointer validation from the current chunk, then retain locality hints
	// as marking walks into older chunks.
	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTChunkHead)
	e.MovDerefReg(amd64.R15, amd64RTMarkChunk, amd64.RAX)

	// Mark exact roots from the linked shadow-root frames.
	e.MovRegDeref(amd64.R12, amd64.R15, amd64RTRootHead)
	frameLoop := len(e.Code)
	e.TestRegReg(amd64.R12, amd64.R12)
	markDoneJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R13, amd64.R12, 8) // root count
	e.MovRegReg(amd64.R14, amd64.R12)
	e.AddRegImm32(amd64.R14, 16) // first root slot

	rootLoop := len(e.Code)
	e.TestRegReg(amd64.R13, amd64.R13)
	frameNextJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R14, 0)
	markRootCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markRootCall + 5)))
	e.AddRegImm32(amd64.R14, 8)
	e.SubRegImm32(amd64.R13, 1)
	rootBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(rootBack, rootLoop)

	frameNext := len(e.Code)
	patchJcc(frameNextJump, frameNext)
	e.MovRegDeref(amd64.R12, amd64.R12, 0)
	frameBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(frameBack, frameLoop)

	markDone := len(e.Code)
	patchJcc(markDoneJump, markDone)

	// The runnable queue is a runtime-owned GC root. Marking its head is enough
	// because task tracing follows the next pointer through the complete queue.
	e.MovRegDeref(amd64.RDI, amd64.R15, amd64RTTaskHead)
	markTaskQueueCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskQueueCall + 5)))
	e.MovRegDeref(amd64.RDI, amd64.R15, amd64RTTimerHead)
	markTimerQueueCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTimerQueueCall + 5)))
	e.MovRegDeref(amd64.RDI, amd64.R15, amd64RTCurrentTask)
	markCurrentTaskCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markCurrentTaskCall + 5)))

	// Drain the intrusive mark worklist. Newly discovered children are pushed by
	// ts_gc_mark_payload, so every reachable object is traced exactly once.
	traceWorkLoop := len(e.Code)
	e.MovRegDeref(amd64.R12, amd64.R15, amd64RTFreeList)
	e.TestRegReg(amd64.R12, amd64.R12)
	traceDoneJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R13, amd64.R12, amd64ObjectNextFree)
	e.MovDerefReg(amd64.R15, amd64RTFreeList, amd64.R13)
	e.MovRegImm64(amd64.RAX, 0)
	e.MovDerefReg(amd64.R12, amd64ObjectNextFree, amd64.RAX)
	e.MovRegDeref(amd64.RAX, amd64.R12, amd64ObjectType)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeArray))
	isArray := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeRefData))
	isRefData := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeObject))
	isObject := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeClosure))
	isClosure := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeJSValueData))
	isJSValueData := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeDynamicObject))
	isDynamicObject := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeDynamicEntries))
	isDynamicEntries := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeTask))
	isTask := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeChannel))
	isChannel := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeTaskGroup))
	isTaskGroup := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeCollection))
	isCollection := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	traceAfterChildrenJump := len(e.Code)
	e.JmpRel32(0)

	traceArray := len(e.Code)
	patchJcc(isArray, traceArray)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64ArrayData)
	markArrayChildCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markArrayChildCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceArrayDone := len(e.Code)
	e.JmpRel32(0)

	traceRefData := len(e.Code)
	patchJcc(isRefData, traceRefData)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectSize)
	e.SubRegImm32(amd64.R9, amd64ObjectHeaderSize)
	e.ShrRegImm8(amd64.R9, 3)
	refSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	refSlotsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markRefCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markRefCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.R8, 8)
	e.SubRegImm32(amd64.R9, 1)
	refSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(refSlotBack, refSlotLoop)
	refSlotsDoneLabel := len(e.Code)
	patchJcc(refSlotsDone, refSlotsDoneLabel)
	traceRefDataDone := len(e.Code)
	e.JmpRel32(0)

	traceObjectFields := len(e.Code)
	patchJcc(isObject, traceObjectFields)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize+amd64ObjectFields)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectHeaderSize+amd64ObjectRefMask)
	objectFieldLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	objectFieldsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.R9)
	e.MovRegImm64(amd64.R11, 1)
	e.AndRegReg(amd64.R10, amd64.R11)
	e.TestRegReg(amd64.R10, amd64.R10)
	skipObjectField := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markObjectFieldCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markObjectFieldCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	objectFieldNext := len(e.Code)
	patchJcc(skipObjectField, objectFieldNext)
	e.AddRegImm32(amd64.R8, 8)
	e.ShrRegImm8(amd64.R9, 1)
	objectFieldBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(objectFieldBack, objectFieldLoop)
	objectFieldsDoneLabel := len(e.Code)
	patchJcc(objectFieldsDone, objectFieldsDoneLabel)
	traceObjectDone := len(e.Code)
	e.JmpRel32(0)

	// JSValue backing stores trace only tagged heap references.
	traceJSValueData := len(e.Code)
	patchJcc(isJSValueData, traceJSValueData)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectSize)
	e.SubRegImm32(amd64.R9, amd64ObjectHeaderSize)
	e.ShrRegImm8(amd64.R9, 3)
	jsSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	jsSlotsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markJSCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markJSCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.R8, 8)
	e.SubRegImm32(amd64.R9, 1)
	jsSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(jsSlotBack, jsSlotLoop)
	jsSlotsDoneLabel := len(e.Code)
	patchJcc(jsSlotsDone, jsSlotsDoneLabel)
	traceJSValueDataDone := len(e.Code)
	e.JmpRel32(0)

	// Dynamic object identity owns one raw pointer to its growable entry table.
	traceDynamicObject := len(e.Code)
	patchJcc(isDynamicObject, traceDynamicObject)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64DynamicEntries)
	markDynamicEntriesCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markDynamicEntriesCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceDynamicObjectDone := len(e.Code)
	e.JmpRel32(0)

	// Dynamic hash entries are {hash, raw string key, boxed JSValue}. Hash words
	// are scalars and must never be interpreted as heap references.
	traceDynamicEntries := len(e.Code)
	patchJcc(isDynamicEntries, traceDynamicEntries)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.RAX, amd64.R12, amd64ObjectSize)
	e.SubRegImm32(amd64.RAX, amd64ObjectHeaderSize)
	e.ShrRegImm8(amd64.RAX, 3) // payload qwords
	e.MovRegImm64(amd64.R11, 3)
	e.Cqo()
	e.IdivReg(amd64.R11)
	e.MovRegReg(amd64.R9, amd64.RAX) // entry count = qwords / 3
	dynamicEntryLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	dynamicEntriesDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, amd64DynamicEntryKey)
	markDynamicKeyCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markDynamicKeyCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R8, amd64DynamicEntryValue)
	markDynamicValueCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markDynamicValueCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.R8, amd64DynamicEntrySize)
	e.SubRegImm32(amd64.R9, 1)
	dynamicEntryBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(dynamicEntryBack, dynamicEntryLoop)
	dynamicEntriesDoneLabel := len(e.Code)
	patchJcc(dynamicEntriesDone, dynamicEntriesDoneLabel)
	traceDynamicEntriesDone := len(e.Code)
	e.JmpRel32(0)

	// Closure payload: code pointer, capture count, reference mask, captures.
	// Only bits set in the capture reference mask are traced.
	traceClosure := len(e.Code)
	patchJcc(isClosure, traceClosure)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize+24)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectHeaderSize+16)
	closureCaptureLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	closureCapturesDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.R9)
	e.MovRegImm64(amd64.R11, 1)
	e.AndRegReg(amd64.R10, amd64.R11)
	e.TestRegReg(amd64.R10, amd64.R10)
	skipClosureCapture := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markClosureCaptureCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markClosureCaptureCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	closureCaptureNext := len(e.Code)
	patchJcc(skipClosureCapture, closureCaptureNext)
	e.AddRegImm32(amd64.R8, 8)
	e.ShrRegImm8(amd64.R9, 1)
	closureCaptureBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(closureCaptureBack, closureCaptureLoop)
	closureCapturesDoneLabel := len(e.Code)
	patchJcc(closureCapturesDone, closureCapturesDoneLabel)
	traceClosureDone := len(e.Code)
	e.JmpRel32(0)

	traceTask := len(e.Code)
	patchJcc(isTask, traceTask)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskClosure)
	markTaskClosureCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskClosureCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskNext)
	markTaskNextCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskNextCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskParent)
	markTaskParentCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskParentCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskContext)
	markTaskContextCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskContextCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskGroupNext)
	markTaskGroupNextCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskGroupNextCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)

	// A suspended task owns a precise-root chain on its private native stack.
	// Walk those frames exactly like the active runtime root chain.
	e.MovRegDeref(amd64.R8, amd64.R12, amd64ObjectHeaderSize+amd64TaskSavedRoot)
	taskRootFrameLoop := len(e.Code)
	e.TestRegReg(amd64.R8, amd64.R8)
	taskRootsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R9, amd64.R8, 8)
	e.MovRegReg(amd64.RDX, amd64.R8)
	e.AddRegImm32(amd64.RDX, 16)
	taskRootSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	taskRootFrameNext := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.RDX, 0)
	markTaskSavedRootCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskSavedRootCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.RDX, 8)
	e.SubRegImm32(amd64.R9, 1)
	taskRootSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(taskRootSlotBack, taskRootSlotLoop)
	taskRootFrameNextLabel := len(e.Code)
	patchJcc(taskRootFrameNext, taskRootFrameNextLabel)
	e.MovRegDeref(amd64.R8, amd64.R8, 0)
	taskRootFrameBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(taskRootFrameBack, taskRootFrameLoop)
	taskRootsDoneLabel := len(e.Code)
	patchJcc(taskRootsDone, taskRootsDoneLabel)

	// While a nested child runs, its return-root chain belongs to the caller
	// stack that resumed it. Trace it until the child yields/completes and clears
	// the return context.
	e.MovRegDeref(amd64.R8, amd64.R12, amd64ObjectHeaderSize+amd64TaskReturnRoot)
	taskReturnFrameLoop := len(e.Code)
	e.TestRegReg(amd64.R8, amd64.R8)
	taskReturnRootsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R9, amd64.R8, 8)
	e.MovRegReg(amd64.RDX, amd64.R8)
	e.AddRegImm32(amd64.RDX, 16)
	taskReturnSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	taskReturnFrameNext := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.RDX, 0)
	markTaskReturnRootCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskReturnRootCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.RDX, 8)
	e.SubRegImm32(amd64.R9, 1)
	taskReturnSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(taskReturnSlotBack, taskReturnSlotLoop)
	taskReturnFrameNextLabel := len(e.Code)
	patchJcc(taskReturnFrameNext, taskReturnFrameNextLabel)
	e.MovRegDeref(amd64.R8, amd64.R8, 0)
	taskReturnFrameBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(taskReturnFrameBack, taskReturnFrameLoop)
	taskReturnRootsDoneLabel := len(e.Code)
	patchJcc(taskReturnRootsDone, taskReturnRootsDoneLabel)

	// Rejection reasons are always JSValue payloads regardless of the declared
	// fulfilled result kind. Fulfilled tasks only trace ref/JS result classes.
	e.MovRegDeref(amd64.R10, amd64.R12, amd64ObjectHeaderSize+amd64TaskState)
	e.CmpRegImm32(amd64.R10, 3)
	traceRejectedResult := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R10, amd64.R12, amd64ObjectHeaderSize+amd64TaskKind)
	e.CmpRegImm32(amd64.R10, int32(amd64TaskResultRef))
	traceTaskResult := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	traceTaskDone := len(e.Code)
	e.JmpRel32(0)
	traceTaskResultLabel := len(e.Code)
	patchJcc(traceRejectedResult, traceTaskResultLabel)
	patchJcc(traceTaskResult, traceTaskResultLabel)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskResult)
	markTaskResultCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskResultCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceTaskResultDone := len(e.Code)
	e.JmpRel32(0)

	traceCollection := len(e.Code)
	patchJcc(isCollection, traceCollection)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64CollectionEntries)
	markCollectionEntriesCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markCollectionEntriesCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceCollectionDone := len(e.Code)
	e.JmpRel32(0)

	traceTaskGroup := len(e.Code)
	patchJcc(isTaskGroup, traceTaskGroup)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64TaskGroupHead)
	markTaskGroupHeadCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markTaskGroupHeadCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceTaskGroupDone := len(e.Code)
	e.JmpRel32(0)

	traceChannel := len(e.Code)
	patchJcc(isChannel, traceChannel)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64ChannelData)
	markChannelDataCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markChannelDataCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64ChannelPending)
	markChannelPendingCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markChannelPendingCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceChannelDone := len(e.Code)
	e.JmpRel32(0)

	traceChildrenDone := len(e.Code)
	patchJmp(traceAfterChildrenJump, traceChildrenDone)
	patchJmp(traceArrayDone, traceChildrenDone)
	patchJmp(traceRefDataDone, traceChildrenDone)
	patchJmp(traceObjectDone, traceChildrenDone)
	patchJmp(traceJSValueDataDone, traceChildrenDone)
	patchJmp(traceDynamicObjectDone, traceChildrenDone)
	patchJmp(traceDynamicEntriesDone, traceChildrenDone)
	patchJmp(traceClosureDone, traceChildrenDone)
	patchJmp(traceTaskDone, traceChildrenDone)
	patchJmp(traceTaskResultDone, traceChildrenDone)
	patchJmp(traceChannelDone, traceChildrenDone)
	patchJmp(traceTaskGroupDone, traceChildrenDone)
	patchJmp(traceCollectionDone, traceChildrenDone)
	traceWorkBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(traceWorkBack, traceWorkLoop)
	traceDone := len(e.Code)
	patchJcc(traceDoneJump, traceDone)

	// Sweep every object in every chunk. R12 is the rebuilt free-list head;
	// R14 accumulates bytes newly reclaimed by this collection.
	e.MovRegImm64(amd64.R12, 0)
	e.MovRegImm64(amd64.R14, 0)
	e.MovRegDeref(amd64.R13, amd64.R15, amd64RTChunkHead)

	sweepChunkLoop := len(e.Code)
	e.TestRegReg(amd64.R13, amd64.R13)
	sweepDoneJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.R13)
	e.AddRegImm32(amd64.R10, amd64ChunkSize)
	e.MovRegDeref(amd64.R11, amd64.R13, amd64ChunkUsed)

	sweepObjectLoop := len(e.Code)
	e.CmpRegReg(amd64.R10, amd64.R11)
	nextChunkJump := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	e.MovRegDeref(amd64.RBX, amd64.R10, amd64ObjectSize)
	e.MovRegDeref(amd64.RAX, amd64.R10, amd64ObjectFlags)
	e.CmpRegImm32(amd64.RAX, 1)
	liveJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, 2)
	alreadyFreeJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)

	// Newly unreachable object.
	e.MovRegImm64(amd64.RAX, 2)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RAX)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.R12)
	e.MovRegReg(amd64.R12, amd64.R10)
	e.AddRegReg(amd64.R14, amd64.RBX)
	objectNextJump := len(e.Code)
	e.JmpRel32(0)

	alreadyFree := len(e.Code)
	patchJcc(alreadyFreeJump, alreadyFree)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.R12)
	e.MovRegReg(amd64.R12, amd64.R10)
	freeNextJump := len(e.Code)
	e.JmpRel32(0)

	live := len(e.Code)
	patchJcc(liveJump, live)
	e.MovRegImm64(amd64.RAX, 0)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RAX)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.RAX)

	objectNext := len(e.Code)
	patchJmp(objectNextJump, objectNext)
	patchJmp(freeNextJump, objectNext)
	e.AddRegReg(amd64.R10, amd64.RBX)
	objectBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(objectBack, sweepObjectLoop)

	nextChunk := len(e.Code)
	patchJcc(nextChunkJump, nextChunk)
	e.MovRegDeref(amd64.R13, amd64.R13, amd64ChunkNext)
	chunkBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(chunkBack, sweepChunkLoop)

	sweepDone := len(e.Code)
	patchJcc(sweepDoneJump, sweepDone)
	e.MovDerefReg(amd64.R15, amd64RTFreeList, amd64.R12)
	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTReclaimed)
	e.AddRegReg(amd64.RAX, amd64.R14)
	e.MovDerefReg(amd64.R15, amd64RTReclaimed, amd64.RAX)

	e.Pop(amd64.R14)
	e.Pop(amd64.R13)
	e.Pop(amd64.R12)
	e.Pop(amd64.RBX)
	e.Pop(amd64.RBP)
	e.Ret()
}

func emitAMD64GCMetricNumber(e *amd64.Emitter, contextOffset int32) {
	e.MovRegDeref(amd64.RAX, amd64.R15, contextOffset)
	e.Cvtsi2sd(amd64.XMM0, amd64.RAX)
	e.Ret()
}
