package lower

import (
	"encoding/binary"

	"github.com/phongsathornpt/ts-pro/internal/backend/asm/amd64"
)

func emitAMD64GCMarkPayload(e *amd64.Emitter) {
	patchJcc := func(at, target int) { binary.LittleEndian.PutUint32(e.Code[at+2:], uint32(int32(target-(at+6)))) }
	patchJmp := func(at, target int) { binary.LittleEndian.PutUint32(e.Code[at+1:], uint32(int32(target-(at+5)))) }
	// Accept raw payload pointers and NaN-boxed JSValue references.
	e.MovRegReg(amd64.RAX, amd64.RDI)
	e.MovRegImm64(amd64.R10, amd64JSTagMask)
	e.AndRegReg(amd64.RAX, amd64.R10)
	e.MovRegImm64(amd64.R10, amd64JSStringTag)
	e.CmpRegReg(amd64.RAX, amd64.R10)
	isTaggedString := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegImm64(amd64.R10, amd64JSRefTag)
	e.CmpRegReg(amd64.RAX, amd64.R10)
	rawPayload := len(e.Code)
	e.JccRel32(amd64.CondNE, 0)
	taggedPayload := len(e.Code)
	patchJcc(isTaggedString, taggedPayload)
	e.MovRegImm64(amd64.R10, amd64JSPayloadMask)
	e.AndRegReg(amd64.RDI, amd64.R10)
	patchJcc(rawPayload, len(e.Code))
	e.TestRegReg(amd64.RDI, amd64.RDI)
	nilJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.RDI)
	e.SubRegImm32(amd64.R10, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.R11, amd64.R15, amd64RTChunkHead)
	loop := len(e.Code)
	e.TestRegReg(amd64.R11, amd64.R11)
	missJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.RAX, amd64.R11)
	e.AddRegImm32(amd64.RAX, amd64ChunkSize)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	nextBelow := len(e.Code)
	e.JccRel32(amd64.CondB, 0)
	e.MovRegDeref(amd64.RAX, amd64.R11, amd64ChunkUsed)
	e.CmpRegReg(amd64.R10, amd64.RAX)
	nextAbove := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	e.MovRegDeref(amd64.RAX, amd64.R10, amd64ObjectFlags)
	e.CmpRegImm32(amd64.RAX, 1)
	alreadyMarked := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, 2)
	freeJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegImm64(amd64.RAX, 1)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RAX)
	e.Ret()
	next := len(e.Code)
	patchJcc(nextBelow, next)
	patchJcc(nextAbove, next)
	e.MovRegDeref(amd64.R11, amd64.R11, amd64ChunkNext)
	back := len(e.Code)
	e.JmpRel32(0)
	patchJmp(back, loop)
	zero := len(e.Code)
	patchJcc(nilJump, zero)
	patchJcc(missJump, zero)
	patchJcc(alreadyMarked, zero)
	patchJcc(freeJump, zero)
	e.MovRegImm64(amd64.RAX, 0)
	e.Ret()
}

func emitAMD64GCCollect(e *amd64.Emitter, markOffset int) {
	patchJcc := func(at, target int) {
		binary.LittleEndian.PutUint32(e.Code[at+2:], uint32(int32(target-(at+6))))
	}
	patchJmp := func(at, target int) {
		binary.LittleEndian.PutUint32(e.Code[at+1:], uint32(int32(target-(at+5))))
	}

	e.Push(amd64.RBP)
	e.MovRegReg(amd64.RBP, amd64.RSP)
	e.Push(amd64.RBX)
	e.Push(amd64.R12)
	e.Push(amd64.R13)
	e.Push(amd64.R14)

	// collectionCount++
	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTCollections)
	e.AddRegImm32(amd64.RAX, 1)
	e.MovDerefReg(amd64.R15, amd64RTCollections, amd64.RAX)

	// Mark exact string roots from the linked shadow-root frames.
	e.MovRegDeref(amd64.R12, amd64.R15, amd64RTRootHead)
	frameLoop := len(e.Code)
	e.TestRegReg(amd64.R12, amd64.R12)
	markDoneJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.R13, amd64.R12, 8) // root count
	e.MovRegReg(amd64.R14, amd64.R12)
	e.AddRegImm32(amd64.R14, 16) // first root slot

	rootLoop := len(e.Code)
	e.TestRegReg(amd64.R13, amd64.R13)
	frameNextJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RAX, amd64.R14, 0)
	e.TestRegReg(amd64.RAX, amd64.RAX)
	rootNextIfNil := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.RAX)
	e.MovRegReg(amd64.R8, amd64.RAX)
	e.MovRegImm64(amd64.R9, amd64JSTagMask)
	e.AndRegReg(amd64.R8, amd64.R9)
	e.MovRegImm64(amd64.R9, amd64JSStringTag)
	e.CmpRegReg(amd64.R8, amd64.R9)
	rootString := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegImm64(amd64.R9, amd64JSRefTag)
	e.CmpRegReg(amd64.R8, amd64.R9)
	rootRaw := len(e.Code)
	e.JccRel32(amd64.CondNE, 0)
	rootTagged := len(e.Code)
	patchJcc(rootString, rootTagged)
	e.MovRegImm64(amd64.R9, amd64JSPayloadMask)
	e.AndRegReg(amd64.R10, amd64.R9)
	patchJcc(rootRaw, len(e.Code))
	e.SubRegImm32(amd64.R10, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.R11, amd64.R15, amd64RTChunkHead)

	chunkFindLoop := len(e.Code)
	e.TestRegReg(amd64.R11, amd64.R11)
	rootNextIfNoChunk := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.RBX, amd64.R11)
	e.AddRegImm32(amd64.RBX, amd64ChunkSize)
	e.CmpRegReg(amd64.R10, amd64.RBX)
	chunkNextIfBelow := len(e.Code)
	e.JccRel32(amd64.CondB, 0)
	e.MovRegDeref(amd64.RBX, amd64.R11, amd64ChunkUsed)
	e.CmpRegReg(amd64.R10, amd64.RBX)
	chunkNextIfAbove := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)

	// Exact heap payload found. Mark its header.
	e.MovRegImm64(amd64.RBX, 1)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RBX)
	rootMarkedJump := len(e.Code)
	e.JmpRel32(0)

	chunkNext := len(e.Code)
	patchJcc(chunkNextIfBelow, chunkNext)
	patchJcc(chunkNextIfAbove, chunkNext)
	e.MovRegDeref(amd64.R11, amd64.R11, amd64ChunkNext)
	chunkFindBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(chunkFindBack, chunkFindLoop)

	rootNext := len(e.Code)
	patchJcc(rootNextIfNil, rootNext)
	patchJcc(rootNextIfNoChunk, rootNext)
	patchJmp(rootMarkedJump, rootNext)
	e.AddRegImm32(amd64.R14, 8)
	e.SubRegImm32(amd64.R13, 1)
	rootBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(rootBack, rootLoop)

	frameNext := len(e.Code)
	patchJcc(frameNextJump, frameNext)
	e.MovRegDeref(amd64.R12, amd64.R12, 0)
	frameBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(frameBack, frameLoop)

	markDone := len(e.Code)
	patchJcc(markDoneJump, markDone)

	// Propagate marks through array objects and reference backing stores until
	// a fixed point is reached. Atomic strings/scalar backing stores have no children.
	tracePass := len(e.Code)
	e.MovRegImm64(amd64.R14, 0) // changed
	e.MovRegDeref(amd64.R13, amd64.R15, amd64RTChunkHead)
	traceChunkLoop := len(e.Code)
	e.TestRegReg(amd64.R13, amd64.R13)
	tracePassDoneJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R12, amd64.R13)
	e.AddRegImm32(amd64.R12, amd64ChunkSize)
	e.MovRegDeref(amd64.RBX, amd64.R13, amd64ChunkUsed)
	traceObjectLoop := len(e.Code)
	e.CmpRegReg(amd64.R12, amd64.RBX)
	traceNextChunkJump := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	e.MovRegDeref(amd64.RAX, amd64.R12, amd64ObjectFlags)
	e.CmpRegImm32(amd64.RAX, 1)
	traceObjectNextJump := len(e.Code)
	e.JccRel32(amd64.CondNE, 0)
	e.MovRegDeref(amd64.RAX, amd64.R12, amd64ObjectType)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeArray))
	isArray := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeRefData))
	isRefData := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeObject))
	isObject := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeClosure))
	isClosure := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, int32(amd64ObjectTypeJSValueData))
	isJSValueData := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	traceAfterChildrenJump := len(e.Code)
	e.JmpRel32(0)

	traceArray := len(e.Code)
	patchJcc(isArray, traceArray)
	e.MovRegDeref(amd64.RDI, amd64.R12, amd64ObjectHeaderSize+amd64ArrayData)
	markArrayChildCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markArrayChildCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	traceArrayDone := len(e.Code)
	e.JmpRel32(0)

	traceRefData := len(e.Code)
	patchJcc(isRefData, traceRefData)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectSize)
	e.SubRegImm32(amd64.R9, amd64ObjectHeaderSize)
	e.ShrRegImm8(amd64.R9, 3)
	refSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	refSlotsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markRefCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markRefCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.R8, 8)
	e.SubRegImm32(amd64.R9, 1)
	refSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(refSlotBack, refSlotLoop)
	refSlotsDoneLabel := len(e.Code)
	patchJcc(refSlotsDone, refSlotsDoneLabel)
	traceRefDataDone := len(e.Code)
	e.JmpRel32(0)

	traceObjectFields := len(e.Code)
	patchJcc(isObject, traceObjectFields)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize+amd64ObjectFields)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectHeaderSize+amd64ObjectRefMask)
	objectFieldLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	objectFieldsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.R9)
	e.MovRegImm64(amd64.R11, 1)
	e.AndRegReg(amd64.R10, amd64.R11)
	e.TestRegReg(amd64.R10, amd64.R10)
	skipObjectField := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markObjectFieldCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markObjectFieldCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	objectFieldNext := len(e.Code)
	patchJcc(skipObjectField, objectFieldNext)
	e.AddRegImm32(amd64.R8, 8)
	e.ShrRegImm8(amd64.R9, 1)
	objectFieldBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(objectFieldBack, objectFieldLoop)
	objectFieldsDoneLabel := len(e.Code)
	patchJcc(objectFieldsDone, objectFieldsDoneLabel)
	traceObjectDone := len(e.Code)
	e.JmpRel32(0)

	// JSValue backing stores trace only tagged heap references.
	traceJSValueData := len(e.Code)
	patchJcc(isJSValueData, traceJSValueData)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectSize)
	e.SubRegImm32(amd64.R9, amd64ObjectHeaderSize)
	e.ShrRegImm8(amd64.R9, 3)
	jsSlotLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	jsSlotsDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markJSCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markJSCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	e.AddRegImm32(amd64.R8, 8)
	e.SubRegImm32(amd64.R9, 1)
	jsSlotBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(jsSlotBack, jsSlotLoop)
	jsSlotsDoneLabel := len(e.Code)
	patchJcc(jsSlotsDone, jsSlotsDoneLabel)
	traceJSValueDataDone := len(e.Code)
	e.JmpRel32(0)

	// Closure payload: code pointer, capture count, reference mask, captures.
	// Only bits set in the capture reference mask are traced.
	traceClosure := len(e.Code)
	patchJcc(isClosure, traceClosure)
	e.MovRegReg(amd64.R8, amd64.R12)
	e.AddRegImm32(amd64.R8, amd64ObjectHeaderSize+24)
	e.MovRegDeref(amd64.R9, amd64.R12, amd64ObjectHeaderSize+16)
	closureCaptureLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	closureCapturesDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.R9)
	e.MovRegImm64(amd64.R11, 1)
	e.AndRegReg(amd64.R10, amd64.R11)
	e.TestRegReg(amd64.R10, amd64.R10)
	skipClosureCapture := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegDeref(amd64.RDI, amd64.R8, 0)
	markClosureCaptureCall := len(e.Code)
	e.CallRel32(int32(markOffset - (markClosureCaptureCall + 5)))
	e.OrRegReg(amd64.R14, amd64.RAX)
	closureCaptureNext := len(e.Code)
	patchJcc(skipClosureCapture, closureCaptureNext)
	e.AddRegImm32(amd64.R8, 8)
	e.ShrRegImm8(amd64.R9, 1)
	closureCaptureBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(closureCaptureBack, closureCaptureLoop)
	closureCapturesDoneLabel := len(e.Code)
	patchJcc(closureCapturesDone, closureCapturesDoneLabel)

	traceChildrenDone := len(e.Code)
	patchJmp(traceAfterChildrenJump, traceChildrenDone)
	patchJmp(traceArrayDone, traceChildrenDone)
	patchJmp(traceRefDataDone, traceChildrenDone)
	patchJmp(traceObjectDone, traceChildrenDone)
	patchJmp(traceJSValueDataDone, traceChildrenDone)
	traceObjectNext := len(e.Code)
	patchJcc(traceObjectNextJump, traceObjectNext)
	e.MovRegDeref(amd64.RAX, amd64.R12, amd64ObjectSize)
	e.AddRegReg(amd64.R12, amd64.RAX)
	traceObjectBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(traceObjectBack, traceObjectLoop)
	traceNextChunk := len(e.Code)
	patchJcc(traceNextChunkJump, traceNextChunk)
	e.MovRegDeref(amd64.R13, amd64.R13, amd64ChunkNext)
	traceChunkBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(traceChunkBack, traceChunkLoop)
	tracePassDone := len(e.Code)
	patchJcc(tracePassDoneJump, tracePassDone)
	e.TestRegReg(amd64.R14, amd64.R14)
	traceAgain := len(e.Code)
	e.JccRel32(amd64.CondNE, 0)
	patchJcc(traceAgain, tracePass)

	// Sweep every object in every chunk. R12 is the rebuilt free-list head;
	// R14 accumulates bytes newly reclaimed by this collection.
	e.MovRegImm64(amd64.R12, 0)
	e.MovRegImm64(amd64.R14, 0)
	e.MovRegDeref(amd64.R13, amd64.R15, amd64RTChunkHead)

	sweepChunkLoop := len(e.Code)
	e.TestRegReg(amd64.R13, amd64.R13)
	sweepDoneJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovRegReg(amd64.R10, amd64.R13)
	e.AddRegImm32(amd64.R10, amd64ChunkSize)
	e.MovRegDeref(amd64.R11, amd64.R13, amd64ChunkUsed)

	sweepObjectLoop := len(e.Code)
	e.CmpRegReg(amd64.R10, amd64.R11)
	nextChunkJump := len(e.Code)
	e.JccRel32(amd64.CondAE, 0)
	e.MovRegDeref(amd64.RBX, amd64.R10, amd64ObjectSize)
	e.MovRegDeref(amd64.RAX, amd64.R10, amd64ObjectFlags)
	e.CmpRegImm32(amd64.RAX, 1)
	liveJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, 2)
	alreadyFreeJump := len(e.Code)
	e.JccRel32(amd64.CondE, 0)

	// Newly unreachable object.
	e.MovRegImm64(amd64.RAX, 2)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RAX)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.R12)
	e.MovRegReg(amd64.R12, amd64.R10)
	e.AddRegReg(amd64.R14, amd64.RBX)
	objectNextJump := len(e.Code)
	e.JmpRel32(0)

	alreadyFree := len(e.Code)
	patchJcc(alreadyFreeJump, alreadyFree)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.R12)
	e.MovRegReg(amd64.R12, amd64.R10)
	freeNextJump := len(e.Code)
	e.JmpRel32(0)

	live := len(e.Code)
	patchJcc(liveJump, live)
	e.MovRegImm64(amd64.RAX, 0)
	e.MovDerefReg(amd64.R10, amd64ObjectFlags, amd64.RAX)
	e.MovDerefReg(amd64.R10, amd64ObjectNextFree, amd64.RAX)

	objectNext := len(e.Code)
	patchJmp(objectNextJump, objectNext)
	patchJmp(freeNextJump, objectNext)
	e.AddRegReg(amd64.R10, amd64.RBX)
	objectBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(objectBack, sweepObjectLoop)

	nextChunk := len(e.Code)
	patchJcc(nextChunkJump, nextChunk)
	e.MovRegDeref(amd64.R13, amd64.R13, amd64ChunkNext)
	chunkBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(chunkBack, sweepChunkLoop)

	sweepDone := len(e.Code)
	patchJcc(sweepDoneJump, sweepDone)
	e.MovDerefReg(amd64.R15, amd64RTFreeList, amd64.R12)
	e.MovRegDeref(amd64.RAX, amd64.R15, amd64RTReclaimed)
	e.AddRegReg(amd64.RAX, amd64.R14)
	e.MovDerefReg(amd64.R15, amd64RTReclaimed, amd64.RAX)

	e.Pop(amd64.R14)
	e.Pop(amd64.R13)
	e.Pop(amd64.R12)
	e.Pop(amd64.RBX)
	e.Pop(amd64.RBP)
	e.Ret()
}

func emitAMD64GCMetricNumber(e *amd64.Emitter, contextOffset int32) {
	e.MovRegDeref(amd64.RAX, amd64.R15, contextOffset)
	e.Cvtsi2sd(amd64.XMM0, amd64.RAX)
	e.Ret()
}
