package lower

import (
	"encoding/binary"

	"github.com/phongsathornpt/ts-pro/internal/backend/asm/amd64"
)

// emitAMD64JSONParseScalar parses the scalar JSON subset used at dynamic
// string boundaries: signed decimal numbers, true, false, and null.
// RDI = native string, RAX = boxed/raw JSValue.
func emitAMD64JSONParseScalar(e *amd64.Emitter) {
	patchJcc := func(at, target int) { binary.LittleEndian.PutUint32(e.Code[at+2:], uint32(int32(target-(at+6)))) }
	patchJmp := func(at, target int) { binary.LittleEndian.PutUint32(e.Code[at+1:], uint32(int32(target-(at+5)))) }
	e.MovRegDeref(amd64.R9, amd64.RDI, 0)
	e.MovRegReg(amd64.R8, amd64.RDI)
	e.AddRegImm32(amd64.R8, 8)
	// Skip JSON whitespace.
	spaceLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	empty := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovzxRegDeref8(amd64.RAX, amd64.R8, 0)
	var whitespace []int
	for _, ch := range []int32{' ', '\t', '\n', '\r'} {
		e.CmpRegImm32(amd64.RAX, ch)
		at := len(e.Code)
		e.JccRel32(amd64.CondE, 0)
		whitespace = append(whitespace, at)
	}
	spaceDoneJump := len(e.Code)
	e.JmpRel32(0)
	consumeSpace := len(e.Code)
	for _, at := range whitespace {
		patchJcc(at, consumeSpace)
	}
	e.AddRegImm32(amd64.R8, 1)
	e.SubRegImm32(amd64.R9, 1)
	backSpace := len(e.Code)
	e.JmpRel32(0)
	patchJmp(backSpace, spaceLoop)
	spaceDone := len(e.Code)
	patchJmp(spaceDoneJump, spaceDone)
	// Keywords by first byte are unambiguous for valid JSON.
	e.CmpRegImm32(amd64.RAX, 't')
	isTrue := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, 'f')
	isFalse := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, 'n')
	isNull := len(e.Code)
	e.JccRel32(amd64.CondE, 0)

	// Number parser. R10=negative flag, R11=integer, RCX=fraction, RSI=scale.
	e.MovRegImm64(amd64.R10, 0)
	e.MovRegImm64(amd64.R11, 0)
	e.MovRegImm64(amd64.RCX, 0)
	e.MovRegImm64(amd64.RSI, 1)
	e.CmpRegImm32(amd64.RAX, '-')
	notNegative := len(e.Code)
	e.JccRel32(amd64.CondNE, 0)
	e.MovRegImm64(amd64.R10, 1)
	e.AddRegImm32(amd64.R8, 1)
	e.SubRegImm32(amd64.R9, 1)
	notNegativeLabel := len(e.Code)
	patchJcc(notNegative, notNegativeLabel)
	intLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	intDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovzxRegDeref8(amd64.RAX, amd64.R8, 0)
	e.CmpRegImm32(amd64.RAX, '.')
	decimal := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.CmpRegImm32(amd64.RAX, '0')
	intDoneLow := len(e.Code)
	e.JccRel32(amd64.CondB, 0)
	e.CmpRegImm32(amd64.RAX, '9')
	intDoneHigh := len(e.Code)
	e.JccRel32(amd64.CondA, 0)
	e.SubRegImm32(amd64.RAX, '0')
	e.MovRegImm64(amd64.RDX, 10)
	e.ImulRegReg(amd64.R11, amd64.RDX)
	e.AddRegReg(amd64.R11, amd64.RAX)
	e.AddRegImm32(amd64.R8, 1)
	e.SubRegImm32(amd64.R9, 1)
	intBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(intBack, intLoop)
	decimalLabel := len(e.Code)
	patchJcc(decimal, decimalLabel)
	e.AddRegImm32(amd64.R8, 1)
	e.SubRegImm32(amd64.R9, 1)
	fracLoop := len(e.Code)
	e.TestRegReg(amd64.R9, amd64.R9)
	fracDone := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovzxRegDeref8(amd64.RAX, amd64.R8, 0)
	e.CmpRegImm32(amd64.RAX, '0')
	fracDoneLow := len(e.Code)
	e.JccRel32(amd64.CondB, 0)
	e.CmpRegImm32(amd64.RAX, '9')
	fracDoneHigh := len(e.Code)
	e.JccRel32(amd64.CondA, 0)
	e.SubRegImm32(amd64.RAX, '0')
	e.MovRegImm64(amd64.RDX, 10)
	e.ImulRegReg(amd64.RCX, amd64.RDX)
	e.AddRegReg(amd64.RCX, amd64.RAX)
	e.ImulRegReg(amd64.RSI, amd64.RDX)
	e.AddRegImm32(amd64.R8, 1)
	e.SubRegImm32(amd64.R9, 1)
	fracBack := len(e.Code)
	e.JmpRel32(0)
	patchJmp(fracBack, fracLoop)
	finish := len(e.Code)
	patchJcc(intDone, finish)
	patchJcc(intDoneLow, finish)
	patchJcc(intDoneHigh, finish)
	patchJcc(fracDone, finish)
	patchJcc(fracDoneLow, finish)
	patchJcc(fracDoneHigh, finish)
	e.Cvtsi2sd(amd64.XMM0, amd64.R11)
	e.Cvtsi2sd(amd64.XMM1, amd64.RCX)
	e.Cvtsi2sd(amd64.XMM2, amd64.RSI)
	e.DivSD(amd64.XMM1, amd64.XMM2)
	e.AddSD(amd64.XMM0, amd64.XMM1)
	e.TestRegReg(amd64.R10, amd64.R10)
	positive := len(e.Code)
	e.JccRel32(amd64.CondE, 0)
	e.MovQRegXMM(amd64.RAX, amd64.XMM0)
	e.MovRegImm64(amd64.RDX, int64(-0x8000000000000000))
	e.OrRegReg(amd64.RAX, amd64.RDX)
	e.MovQXMMReg(amd64.XMM0, amd64.RAX)
	positiveLabel := len(e.Code)
	patchJcc(positive, positiveLabel)
	e.MovQRegXMM(amd64.RAX, amd64.XMM0)
	e.Ret()

	trueLabel := len(e.Code)
	patchJcc(isTrue, trueLabel)
	e.MovRegImm64(amd64.RAX, amd64JSBoolTag|1)
	e.Ret()
	falseLabel := len(e.Code)
	patchJcc(isFalse, falseLabel)
	e.MovRegImm64(amd64.RAX, amd64JSBoolTag)
	e.Ret()
	nullLabel := len(e.Code)
	patchJcc(isNull, nullLabel)
	e.MovRegImm64(amd64.RAX, amd64NullBits)
	e.Ret()
	emptyLabel := len(e.Code)
	patchJcc(empty, emptyLabel)
	e.MovRegImm64(amd64.RAX, amd64UndefinedBits)
	e.Ret()
}
